# Wights (snow)
skins.1=8-10
biomes.1=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean

# Mummies (sand)
skins.2=11
biomes.2=desert savanna savanna_plateau windswept_savanna badlands eroded_badlands wooded_badlands warm_ocean

# Overgrown (jungle/swamp)
skins.3=12-15
biomes.3=jungle sparse_jungle bamboo_jungle swamp mangrove_swamp dark_forest lush_caves

# Zombies and Goblins (default)
skins.4=1-7