# Sand
skins.1=2
biomes.1=desert savanna savanna_plateau windswept_savanna badlands eroded_badlands wooded_badlands warm_ocean

# Snow
skins.2=3
biomes.2=snowy_plains ice_spikes snowy_taiga grove snowy_slopes frozen_peaks jagged_peaks frozen_river snowy_beach frozen_ocean deep_frozen_ocean

# Jungle
skins.3=4
biomes.3=jungle sparse_jungle bamboo_jungle

# Swamp
skins.4=5
biomes.4=swamp mangrove_swamp dark_forest lush_caves