name: Build pack zip and upload to Revival CDN
on:
  push:
    branches:
    - '1.20'
jobs:
  Build-Pack:
    name: Build pack zip and upload
    runs-on: ubuntu-latest
    steps:
    - name: Download pack files
      uses: actions/checkout@v4
    - name: Remove files with uppercase letters in filepath
      run: find . -path '*[[:upper:]]*' -type f -delete
    - name: Remove all PSDs
      run: find . -name '*.psd' -type f -delete
    - name: Remove all empty directories
      run: find . -empty -type d -delete
    - name: Zip files
      run: mkdir out && zip -r out/Revival-20.zip assets pack.mcmeta pack.png
    - name: Upload to CDN
      uses: ryand56/r2-upload-action@latest
      with:
        r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
        r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
        r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        r2-bucket: revival
        source-dir: out
        destination-dir: ./
